 #
 # Copyright (C) 2023 Sky UK
 #
 # This library is free software; you can redistribute it and/or
 # modify it under the terms of the GNU Lesser General Public
 # License as published by the Free Software Foundation;
 # version 2.1 of the License.
 #
 # This library is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 # Lesser General Public License for more details.
 #
 # You should have received a copy of the GNU Lesser General Public
 # License along with this library; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 #

name: commit-message-format

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request to master and release/* branches
  pull_request:
    branches: ["master", "release/*"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job checks the commit message of the merge
  check-commit-message:
    name: Check Commit Message

    # Runs on ubuntu
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Post commit message comment on PR
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            Pull request title must follow the pattern:
            < JIRA TICKET >: < one line summary of change less than 65 characters >

            Pull request description must follow the Commit message format for RDK-E:
            https://etwiki.sys.comcast.net/spaces/RDKAR/pages/1407997180/Commit+Message+Format+For+RDKE

            1. Associated JIRA ticket in format : < JIRA TICKET >: < one line summary of change less than 65 characters >
            2. Detailed reason for change information
            3. Test procedure. Only references links to Jira ticket or sub tickets where test steps and references are captured.

            < JIRA TICKET >: < one line summary of change less than 65 characters >
            < empty line >
            Reason for change: <explanation of change>
            Test Procedure: < https://ccp.sys.comcast.net/browse/JIRA TICKET/url/to/test_step_section>

      # Check PR title
      - name: Match PR title
        uses: actions-ecosystem/action-regex-match@v2
        id: pr-title-match
        if: failure() || success()
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^[A-Z][A-Z0-9]+-\d+: .{1,64}$'

      # Check PR body
      - name: Match PR Body
        uses: actions-ecosystem/action-regex-match@v2
        id: pr-body-match
        if: failure() || success()
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '^([A-Z][A-Z0-9]+-\d+): (.{1,64})\r?\n\r?\nReason for change:([\s\S]*?)(?:\r?\nTest Procedure:([\s\S]*))?$'

      - name: Check Commit message
        if: (failure() || success()) && (steps.pr-body-match.outputs.match == '')
        run: exit 1
      
      # Print description.
      - name: Log string on failure
        if: failure()
        run: echo ${{ github.event.pull_request.body }}
